[phases.setup]
nixPkgs = ["php82", "nodejs_20"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan view:clear",
  "php artisan migrate --force"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"